### ISSUE TITLE
Open the SARIF file on VsCode have some error

### ISSUE THREAD

**Issue by sf197** [trailofbits/vscode-sarif-explorer#11]
![image](https://github.com/trailofbits/vscode-sarif-explorer/assets/23269932/4294eeba-e9bb-4c26-9b5c-ff4d15988c47)
like this, open the sarif file alert some error.
"TypeError: Cannot read properties of undefined (reading 'replace')."

**Comment by sf197** [comment]
I'm sorry that I can't provide the relevant SARIF file.The SARIF file I generated using the corax tool: [https://github.com/Feysh-Group/corax-community/releases/tag/v2.6](https://github.com/Feysh-Group/corax-community/releases/tag/v2.6)
﻿
Thank you.

**Comment by Vasco-jofra** [comment]
Thanks, I'll check if I can reproduce using corax

**Comment by Vasco-jofra** [comment]
I don't have a great setup to run this tool. Could you, by any chance, be so kind as to run Corax against a random codebase and share the SARIF file with me? With just the error message I was unable to determine what the issue is

**Comment by Vasco-jofra** [comment]
I'm closing this for now since I don't have a reproducible. Hopefully, it was the same issue as in #21 and is fixed! If it ever bothers you again, feel free to reopen the issue
