### ISSUE TITLE
Sarif explorer does not handle output from multiple runs when combined into one SARIF 

### ISSUE THREAD

**Issue by the-storm** [trailofbits/vscode-sarif-explorer#19]
## Context
According to [the SAIRF Schema](https://github.com/oasis-tcs/sarif-spec/blob/main/Schemata/sarif-schema-2.1.0.json#L22-L30), it is possible for a SAIRF output to have the results of multiple runs from multiple tools.
## Problem
Trail of bits Sarif explorer does not handle the results of multiple runs and only processes the first run in the SARIF output
## Example input 
You can load the following SARIF input into the explorer
[test_sarif.json](https://github.com/trailofbits/vscode-sarif-explorer/files/14906143/Untitled-3.json)

* Expected output: one shell injection issue from Tool2
* Actual output: 0 issues output (because the explorer only processed the first run which contained 0 issues)

**Comment by Vasco-jofra** [comment]
Thank you for the report and the reproducible file. We should definitely process multiple runs. I'll take a look soon!

**Comment by Vasco-jofra** [comment]
Closed by #24
