### ISSUE TITLE
URI paths on Windows not working

### ISSUE THREAD

**Issue by peterbrorsson** [trailofbits/vscode-sarif-explorer#31]
It seems like a file uri reference like this:
`file:///d:/sarif/demo.c`
does not work.
This is the correct format according to https://datatracker.ietf.org/doc/html/rfc8089
and is also exemplified in the SARIF documentation (https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html) (just 'find' C:)

It seems like it works in this format:
`file://d:/sarif/demo.c // missing slash`
and
`file://d:\\sarif\\demo.c // missing slash and host path separator`

**Comment by Vasco-jofra** [comment]
Thanks for the report! I haven't used SARIF Explorer on Windows, which is likely why this probably slipped through. I'll try to take a look at this soon. If you have a (non-confidential) SARIF file to reproduce the bug more easily, please share it. If not, I think I get there with your description as well.

**Comment by micaelbo** [comment]
I encounter the same problem. I get the message "Failed to open code region: SarifResultPathIsAbsolute: Result path is absolute but does not exist (/c:/wsl/sarif-test-960/Utilities.c). ..." 

It seems the third "/" in "file:///" ends up in the path.

Example files attached.

[sarif-test-960.zip](https://github.com/user-attachments/files/17735015/sarif-test-960.zip)

**Comment by Vasco-jofra** [comment]
Hey @micaelbo, I think I fixed this issue in #42. Feel free to test the PR and let me know if it is working as you expected.

**Comment by micaelbo** [comment]
Hi @Vasco-jofra. I can confirm that it works with this PR. Thank you.

**Comment by Vasco-jofra** [comment]
Just released a new version with this fixed. Thank you both for the bug report!
